version: '3.3'

services:

  ubuntu-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: ubuntu-vnc
    environment:    
      - VNC_PASSWORD=p4ssw0rd
    ports: 
      - "6080:80" 
      - "5900:5900"
    volumes:
      - ./dev/shm:/dev/shm            
    restart: unless-stopped


